### PR TITLE
[ADD] operators lesson

### PR DESCRIPTION
**Pull request by Koda777**
Hi there,

I've made some updates to the code in this file. Specifically, I added a section on operators and their different types in C programming, including arithmetic, relational, and logical operators. I also provided examples of how to use each type of operator in the main function.

Please take a look and let me know if you have any feedback or suggestions for improvement. Thank you!

### CODE REVIEW

**Review by MintzyG — COMMENTED** [review]
I like the way it is explained but the wall of text seems a bit daunting, maybe interweaving the comments with the code its talking about to give a more immediate example rather than just an explanation could be better, for example:

```
// Relational Operators...
// < less than
if (x < y) { 
    printf("x is less than y"); 
}
// > greater than ....
```

I think people would benefit from having a simple and short lesson on their first read, and when they finish they move on to a submodule about the specific topic where we go more in depth about said topic, we are still brainstorming and you are welcome to give suggestions :)

**Comment by MintzyG** [comment]
for example, the 'variables and types' modules we have right now for C is a bit daunting, what I was thinking we could do is make it a submodule of 'varibles and types' and creating another file to be the module explaining the most used types (int, char, float, double) and give examples in a simple concise way leaving the more in depth explanation of all types to another "lesson" after the person has already learned the basics.

**Comment by MintzyG** [comment]
@Koda777 these are just suggestions and brainstorming since the project is so new and we don't have a format yet, I will wait for your feedback to the ideas before merging  :)

**Review by MintzyG — APPROVED** [review]

**Comment by MintzyG** [comment]
I'll merge, I think this stays up

**Comment by Koda777** [comment]
> for example, the 'variables and types' modules we have right now for C is a bit daunting, what I was thinking we could do is make it a submodule of 'varibles and types' and creating another file to be the module explaining the most used types (int, char, float, double) and give examples in a simple concise way leaving the more in depth explanation of all types to another "lesson" after the person has already learned the basics.

Hi how can we talk about that ? 
Tell me how you want to build the project I'm open

**Comment by grhifen** [comment]
@Koda777 Sorry for the delay, we were busy, @MintzyG will get in touch soon.

**Pull request merged**
